
services:
  app:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: mobilem-laravel
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: mobilem-vue
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    # environment:
    #   - VITE_API_URL=http://localhost:8000/api


  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mobilem
      MYSQL_USER: mobilemuser
      MYSQL_PASSWORD: mobilempass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: